/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package es.mde.alvencar;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
    }
}
